### PR TITLE
model config for stg__catalog_category_product and stg__eav_attribute…

### PR DESCRIPTION
**Pull request by josh-olufemi**
model config for stg__catalog_category_product and stg__eav_attribute_option_value and unique and not_null tests for each PK in every table

### CODE REVIEW

**Comment by djayatillake** [comment]
if you look at the dbt cloud CI test I assume you need to remove some tests from fields that you made a composite key afterwards

**Comment by josh-olufemi** [comment]
I have removed the tests from the relevant columns

**Comment by djayatillake** [comment]
```
Database Error in test not_null_stg__eav_attribute_option_value_composite_key (models/sources/streamkap_current/models.yml)
11:47:24    Unrecognized name: composite_key at [15:7]
11:47:24    compiled SQL at target/run/brandalley_dbt/models/sources/streamkap_current/models.yml/not_null_stg__eav_attribute_option_value_composite_key.sql
11:47:24  
11:47:24  Database Error in test unique_stg__eav_attribute_option_value_composite_key (models/sources/streamkap_current/models.yml)
11:47:24    Unrecognized name: composite_key at [15:9]
11:47:24    compiled SQL at target/run/brandalley_dbt/models/sources/streamkap_current/models.yml/unique_stg__eav_attribute_option_value_composite_key.sql
11:47:24  
11:47:24  Done. PASS=80 WARN=0 ERROR=2 SKIP=0 TOTAL=82
```

You need to full refresh these tables and then the tests will pass as the composite keys will exist

**Comment by josh-olufemi** [comment]
Thank you. I just refreshed both models and re-ran the tests. They all passed. Clean bill of health.

**Pull request merged**
